server:
  port: 8081

inventory:
  service:
    url: http://localhost:8080/api/v1/inventories

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: booking
    # Serializer for producers to send message to the kafka-broker  (Deserializer for consumers)
    consumer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh